{ pkgs, pkgs-unstable, ... }: {
  home.packages = with pkgs; [
    firefox
    thunderbird
    discord
    bitwarden
    element-desktop
    prismlauncher
    vscode
    nixpkgs-fmt
    mangohud
    pavucontrol
    xorg.xev
    evince
    gnome.eog
    tree
    texstudio
    texliveFull
    libsForQt5.konsole
    obs-studio
    vesktop
    libreoffice-qt
    grim
    slurp
    imagemagick
    zip
    qrencode
    gnome.zenity
    icoutils
    gimp
    vlc
    pkgs-unstable.prusa-slicer
  ];
}
