{ pkgs, pkgs-unstable, ... }: {
  home.packages = with pkgs; [
    firefox
    thunderbird
    #https://github.com/bitwarden/clients/issues/8759
    pkgs-unstable.bitwarden-desktop
    element-desktop
    prismlauncher
    vscode
    nixpkgs-fmt
    mangohud
    pavucontrol
    xorg.xev
    evince
    gnome.eog
    tree
    texstudio
    texliveFull
    libsForQt5.konsole
    obs-studio
    vesktop
    libreoffice-qt
    grim
    slurp
    imagemagick
    zip
    qrencode
    gnome.zenity
    icoutils
    gimp
    vlc
    pkgs-unstable.prusa-slicer
  ];
}
